services:
  postgres:
    image: postgres:latest
    container_name: xobot-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: xobot_db
      POSTGRES_PASSWORD: ${DB_PASSWORD:-sofeano333}
    volumes:
      - xobot_pgdata:/var/lib/postgresql/data

volumes:
  xobot_pgdata:
    external: true
    name: e103b788bcdef3ddc5f19cae2562da58ad69682999f9fadf9776a1bf266a6556
